spring.application.name=Catagram

spring.datasource.url=jdbc:postgresql://catagram-db.postgres.database.azure.com:5432/postgres?sslmode=require
spring.datasource.username=zoi4erom@catagram-db
spring.datasource.password=V19761982m
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

cloudinary.cloud-name=dvq30903h
cloudinary.api-key=923631967739551
cloudinary.api-secret=EijjCG3EAm54D4qCnzcH806XmPE

deepl.api.key=331ef623-1eb4-4c00-a1aa-86092b312320:fx